### ISSUE TITLE
How to increase the frequency of FAST LIO2 to 200?

### ISSUE THREAD

**Issue by JACKLiuDay** [hku-mars/Point-LIO#110]
Hello, Doctor He! In your paper, I noticed that in the comparison experiments, the output frequency of FAST LIO2 reached 200Hz. However, in the FAST source code, I can only achieve a 10Hz odometry output. Could you please let me know which parts have been modified to achieve this?

**Comment by migsdigs** [comment]
Hi @JACKLiuDay, did you manage to increase the frequency of the odometry output?
