### ISSUE TITLE
是否在自主无人机上测试过该算法

### ISSUE THREAD

**Issue by MasterY0416** [hku-mars/Point-LIO#13]
目前我掌握的信息显示：对于一个无人机自主导航系统来说，无人机控制需要里程计的频率应该越高越好。作者在自主无人机自主导航系统中测试过该算法吗？从理论上来说该算法很适合用到高速运动的无人机的实时定位上，不知道我的理解是否有错误？

**Comment by Joanna-HE** [comment]
我们在PULSAR上测试过，让pulsar自主飞行，使用的就是point-lio的状态估计输出，不过当时没有测试到很高的输出频率。理论上来说确实适合用到高速运动的无人机上做实时定位的。开源point-lio的代码，也是希望可以提供给社区，继续向下游开发和使用。

**Comment by MasterY0416** [comment]
方便问一下测试频率在多少吗？我们之前在一个慢速的自主无人机上测试过100Hz和400Hz的里程计输出频率，感觉100Hz下自主无人的控制状态更好。
