### ISSUE TITLE
how to deal with my lidar whose point has negative sample time

### ISSUE THREAD

**Issue by ouguangjun** [hku-mars/Point-LIO#15]
My LiDAR is velodyne 16 and  all the point sample time are nagative (about -100~0 ms).  That means the cloud header.stamp is  the end time of the frame?  I found that many other sample time is positive from open source. It confuses me a lot and I  want to know the stamp whether is the begin time or the end time of the frame, so that I can change the code.  Hoping for your reply! Thank you so much!

**Comment by Joanna-HE** [comment]
Hi thanks for your interest in our work, but we did not encounter the negative timestamps when using the velodyne 16, maybe you could provide more information about the negative sample timestamps, and we can talk about here.

**Comment by Joanna-HE** [comment]
Hi, I have an assumption that has not been testified. The negative timestamps indicate that your velodyne does not provide the timestamp for each point. At this time, you should give a timestamp for each point based on the message header time and the scanning pattern of the velodyne.
________________________________
寄件者: Ou guangjun ***@***.***>
寄件日期: 2023年4月4日 下午 03:16
收件者: hku-mars/Point-LIO ***@***.***>
副本: ***@***.*** ***@***.***>; Comment ***@***.***>
主旨: Re: [hku-mars/Point-LIO] how to deal with my lidar whose point has negative sample time (Issue #15)


I print the "pointcloud->points[i].time" and all of them are nagative (-0.1s~0s). The frequence of LiDAR is 10 hz. May be I should ask for the producer. Thanks

**Comment by Joanna-HE** [comment]
You can try the Point-LIO, maybe it is able to handle.

**Comment by ouguangjun** [comment]
I have tried the point-lio before  and found that the code will measure the sample time for each point when the timestamp is not provided. Thank u for your reply!
