### ISSUE TITLE
When I set 'imu_en' to false, nothing will be outputted.

### ISSUE THREAD

**Issue by YYangyuan** [hku-mars/Point-LIO#16]
I modified the code to the following:
if (imu_en){
p_imu->Process(Measures, feats_undistort);
} else {
// p_imu->imu_need_init_ = false;
p_imu->Process(Measures, feats_undistort);
}
but i got a messy map.

**Comment by YYangyuan** [comment]
I tried to change sync_packages() function, and then i got a messy map.

**Comment by Joanna-HE** [comment]
I have fixed this problem, and you could check the new commit of Point-LIO. Thanks for this issue.
