### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by EloyAldao** [hku-mars/Point-LIO#2]
Dear developer

Today you deleted the YouTube video about Point-LIO

Does this means that the project will not be public released or it means that there will be a new video because the paper was accepted and the code will be available?

Hoping the best

Thanks in advance

**Comment by Joanna-HE** [comment]
Thanks for your interest in our work! The YouTube video is deleted due to a policy of the Science Robotics. After the paper of Science Robotics is published on 15th March, 2023, the video would be released again.

Best regards,

Dongjiao He

**Comment by Joanna-HE** [comment]
Hi, thanks for your interest in our work! The video is deleted for a policy of a journal. The video will be released again after 15th March, 2023, and the code would also be public released.

Best regards

Dongjiao He
