### ISSUE TITLE
跑数据集的时候总是飘

### ISSUE THREAD

**Issue by zilong-ding** [hku-mars/Point-LIO#20]
![image](https://user-images.githubusercontent.com/71497754/230545622-f198dff0-3207-4638-ad73-f3db56d2977e.png)
![image](https://user-images.githubusercontent.com/71497754/230546530-d3d3fefc-a095-486a-a867-8ac8124e8924.png)
![image](https://user-images.githubusercontent.com/71497754/230547079-a171c593-832c-4e96-8363-c44899e480d2.png)

我在自己电脑上跑onedrive里面的数据集，分别使用
roslaunch point_lio mapping_avia.launch和
roslaunch point_lio mapping_horizon.launch
对四个数据集（PULSAR.bag   pendulum.bag   racing_drone.bag  'spinning_platform (1).bag'）进行测试，
但是总是有比较明显的偏移（一般是前期比较稳，后面会飘），是相关参数设置不对吗？

**Comment by Joanna-HE** [comment]
pulsar的imu我们重新刷了一下，陀螺仪的量程是17.5，所以要把avia.yaml的’satu_gyro'改为17.5

**Comment by Joanna-HE** [comment]
文章里有写，我刚刚在readme里也添加了这个说明

**Comment by zilong-ding** [comment]
![image](https://user-images.githubusercontent.com/71497754/230573934-6e32e46b-30f2-47c4-b077-dd37543dfe0d.png)
谢谢，效果很棒
