### ISSUE TITLE
预测过程中的控制量输入问题

### ISSUE THREAD

**Issue by yangtzey** [hku-mars/Point-LIO#28]
你好 我在代码看在预测时候 input_in 是从IMU的队列里取得的 也就是说IMU输入 即作为预测又作为观测吗 ？不像论文中提到的使用了随机过程。非常感谢！

**Comment by Joanna-HE** [comment]
你好，代码开源了两种方式，文章中提到了的作为ablation study的point-lio-input也开源了，input_in是在point-lio-input用的，没有在point-lio里面用到。

**Comment by yangtzey** [comment]
这是来自QQ邮箱的假期自动回复邮件。
自动回复

**Comment by yangtzey** [comment]
@Joanna-HE 非常感谢您的回复 谢谢
