### ISSUE TITLE
Are example datasets public?

### ISSUE THREAD

**Issue by Cc19245** [hku-mars/Point-LIO#3]
Hi @Joanna-HE, thanks for your excellent work!

I wonder if Example-1 and Example-2 datasets are publicly available?

**Comment by Joanna-HE** [comment]
Yes, these example datasets will also be published several days later.

**Comment by Joanna-HE** [comment]
Hi, example datasets are public through a onedrive link, please check the Examples section of the Readme.

**Comment by Cc19245** [comment]
> 

Got it, thank you very much!
