### ISSUE TITLE
high-frequency odometer

### ISSUE THREAD

**Issue by MasterBicycle** [hku-mars/Point-LIO#4]
Hello author, this is a great job. I have tested the relevant code, and I checked the topic /aft_mapped_to_init，and it is still only 10Hz. Is there something I have not set correctly?

**Comment by Joanna-HE** [comment]
Hi, thanks for your interest in our work! The option for high frequency odometry output is added in the new commit, you are welcom to follow the note D of 5. directly run of the Readme to obtain high frequency odometry! Thanks for this issue to help me improve the open sourced code.

**Comment by MasterBicycle** [comment]
OK，Thanks！
