### ISSUE TITLE
单次运行时间异常长

### ISSUE THREAD

**Issue by Dy-314** [hku-mars/Point-LIO#50]
自己录的horizon数据包，雷达发送频率为10Hz，单次运行时间在1.3s左右，主要是ICP部分时间异常长。
数据包链接为https://hiylkkhewk.feishu.cn/file/ZN2lbiJMIoTGCSxrFJZc0IcYnWe

**Comment by Dy-314** [comment]
应该是场景基本无变化导致局部点云地图点数过多，致使最近邻搜索时长过长。

**Comment by Joanna-HE** [comment]
The map has a parameter for resolution, maybe you can try to change this parameter to check if this is the reason for unusual long running I have no other ideas about this problem.
