### ISSUE TITLE
mid-70, mid-40 or other livox serial LiDAR 

### ISSUE THREAD

**Issue by MasterBicycle** [hku-mars/Point-LIO#8]
作者你好，我测试了您的算法在 Velodyne 和 Ouster 数据上效果很好，但是在livox激光上运行时出现了下面的问题。我尝试了很多方法，但是没有找到解决办法，你可以给我提供一些建议？

**Comment by MasterBicycle** [comment]
![图片](https://user-images.githubusercontent.com/125568810/227724693-8e02b60b-4f64-4887-9d29-10c08fea9237.png)

**Comment by Joanna-HE** [comment]
请问你用的是livox的内置IMU嘛？检查一下yaml文件中，是否将IMU的量程"acc_satu"和“gyro_satu”以及加速度计的单位“acc_norm”设置对了呢？

**Comment by MasterBicycle** [comment]
感谢你的及时回复，是内置的IMU，这些值采用的是文件中默认值
![图片](https://user-images.githubusercontent.com/125568810/227780145-7ef0ccd1-9354-42b2-83c3-382ef0185ada.png)

**Comment by MasterY0416** [comment]
哦。应该是我加的代码有关系，将点云地图和重力系方向对齐。您有一些好的建议吗
![image](https://user-images.githubusercontent.com/56281050/227780729-1abcfefc-7793-4198-8769-a8354630ba29.png)

**Comment by MasterBicycle** [comment]
哦，应该是和我加的代码有关系，将第一帧点云和重力系方向对齐。但是在Velodyne和Ouster数据下都可以正常运行，您有好的建议吗
![图片](https://user-images.githubusercontent.com/125568810/227781400-2542b4bd-653d-461a-b84d-e2be16102170.png)

**Comment by MasterBicycle** [comment]
谢谢作者的及时回复，现在代码能正常运行了。不过还有个疑问，当把第一帧点云通过重力系对齐后，'use_imu_as_input'设置成1，相对来说对状态估计的结果有很大的影响，我还在进一步学习您的代码，感谢和您的交流。
![图片](https://user-images.githubusercontent.com/125568810/227781891-4ebf1b8e-c1d2-48af-a222-8fd1809abf98.png)

**Comment by Joanna-HE** [comment]
Point-lio是将第一帧的IMU坐标系设为world系的，所以如果要做第一帧点云通过重力系对齐的话，相当于修改了world系，需要相应修改当前状态量中的IMU相对与world系的旋转。

**Comment by MasterY0416** [comment]
恍然大明白，“花”

**Comment by MasterBicycle** [comment]
恍然大明白，“花”
