### ISSUE TITLE
建图的时候会一直往下掉

### ISSUE THREAD

**Issue by johnnychen412** [hku-mars/Point-LIO#89]
![image_2024-06-27_235453918](https://github.com/hku-mars/Point-LIO/assets/140036941/0bc7fd64-7565-41cd-8da8-83e695345e3c)
你好！感谢你优秀的开源代码，我在运行NTU Viral dataset的时候，发现无法正常建图，会一直往下掉。有尝试将gravity设为+9.8也无法改善。用原本您的开源code（还是ikd-tree版本的）在相同的config下却可以正常建图，不知道是什么情况？
以下是我的config文件:
common:
    lid_topic: "/os1_cloud_node1/points" 
    imu_topic: "/imu/imu" 
    con_frame: false # true: if you need to combine several LiDAR frames into one
    con_frame_num: 1 # the number of frames combined
    cut_frame: false # true: if you need to cut one LiDAR frame into several subframes
    cut_frame_time_interval: 0.1 # should be integral fraction of 1 / LiDAR frequency   
    time_diff_lidar_to_imu: 0.0 # Time offset between LiDAR and IMU calibrated by other algorithms, e.g., LI-Init (find in Readme)

preprocess:
    lidar_type: 3
    scan_line: 16
    timestamp_unit: 3           # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 4.0 

mapping:
    imu_en: true
    extrinsic_est_en: false # for aggressive motion, set this variable false
    imu_time_inte: 0.01 # = 1 / frequency of IMU
    lidar_time_inte: 0.1
    satu_acc: 30.0 # the saturation value of IMU's acceleration. not related to the units
    satu_gyro: 35 # the saturation value of IMU's angular velocity. not related to the units
    acc_norm: 9.81 # 1.0 for g as unit, 9.81 for m/s^2 as unit of the IMU's acceleration
    lidar_meas_cov: 0.01 # 0.001
    acc_cov_output: 500
    gyr_cov_output: 1000 
    b_acc_cov: 0.0001 
    b_gyr_cov: 0.0001 
    imu_meas_acc_cov: 0.1 #0.1 # 2
    imu_meas_omg_cov: 0.1 #0.1 # 2 
    gyr_cov_input: 0.01 # for IMU as input model
    acc_cov_input: 0.1 # for IMU as input model
    plane_thr: 0.1 # 0.05, the threshold for plane criteria, the smaller, the flatter a plane
    match_s: 81
    ivox_grid_resolution: 2.0
    gravity: [0.0, 0.0, -9.810] # [-0.30, 0.880, -9.76] # liosam [0.0, 9.810, 0.0] # # preknown gravity, use when imu_en is false or start from a non-stationary state
    gravity_init: [0.0, 0.0, -9.810] # preknown gravity in the initial IMU frame for unstationary start or in the initial LiDAR frame for using without IMU
    extrinsic_T: [ 0.05, 0.0, -0.055] # ulhk # [-0.5, 1.4, 1.5] # utbm
    # extrinsic_R: [ 0, 1, 0,
    #                -1, 0, 0,
    #                0, 0, 1 ] # ulhk 5 6
    # extrinsic_R: [ 0, -1, 0,
    #                 1, 0, 0,
    #                 0, 0, 1 ] # utbm 1, 2
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1 ] # ulhk 4 utbm 3

odometry: 
    publish_odometry_without_downsample: false

publish:
    path_en: true                 # false: close the path output
    scan_publish_en: true         # false: close all the point cloud output
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

**Comment by Joanna-HE** [comment]
可能是加速度计的测量单位没有给对，可以改一下yaml文件中的acc_norm试一下

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: johnnychen412 ***@***.***>
发送时间: Thursday, November 14, 2024 7:38:22 PM
收件人: hku-mars/Point-LIO ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [hku-mars/Point-LIO] 建图的时候会一直往下掉 (Issue #89)


This is an external email.

Closed #89<https://github.com/hku-mars/Point-LIO/issues/89> as completed.

―

**Comment by sanbens** [comment]
贺博你好,请教一下,关于time_diff_lidar_to_imu,我搜了一下最新版本的代码,似乎在程序中只是赋值一下,并未使用?
