### ISSUE TITLE
贺博您好，源码默认版本中使用ivox代替ikdtree的原因是什么呢？

### ISSUE THREAD

**Issue by cchester25** [hku-mars/Point-LIO#95]

**Comment by chenxiaocongAI** [comment]
兄弟，是为什么原因导致使用ivox呢

**Comment by Joanna-HE** [comment]
可以选择你喜欢的地图组织形式。选择ivox的原因主要是它搜索效率更高。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ForNice ***@***.***>
发送时间: Thursday, August 14, 2025 6:28:21 PM
收件人: hku-mars/Point-LIO ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [hku-mars/Point-LIO] 贺博您好，源码默认版本中使用ivox代替ikdtree的原因是什么呢？ (Issue #95)


This is an external email.

[https://avatars.githubusercontent.com/u/40230011?s=20&v=4]chenxiaocongAI left a comment (hku-mars/Point-LIO#95)<https://github.com/hku-mars/Point-LIO/issues/95#issuecomment-3187945826>

兄弟，是为什么原因导致使用ivox呢

―
