### ISSUE TITLE
Mapping Problem on MCD Dataset

### ISSUE THREAD

**Issue by chengwei0427** [hku-mars/Point-LIO#96]
Hi, Dear Author,
Thanks for your nice work.
I have recently been testing your open-source algorithm and noticed some drift when working with MCD data. Could you suggest which parameters I could adjust to optimize the results for this dataset？
![2024-08-29 11-56-13屏幕截图](https://github.com/user-attachments/assets/0ffa6529-2441-45c3-9afe-bfdd74c94d66)
![2024-08-29 11-56-45屏幕截图](https://github.com/user-attachments/assets/2d6ce8fb-7ea3-4b32-a91d-62ae020a079d)
![image](https://github.com/user-attachments/assets/522bcfeb-f4ec-4ec5-b738-da14b3c66814)
Thanks.

**Comment by Joanna-HE** [comment]
Try to set acc_norm = 9.805, satu_acc = 30.0
And set gravity=[0.0, 0.0, -9.805]


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: chengwei ***@***.***>
发送时间: Thursday, August 29, 2024 11:59:13 AM
收件人: hku-mars/Point-LIO ***@***.***>
抄送: Subscribed ***@***.***>
主题: [hku-mars/Point-LIO] Mapping Problem on MCD Dataset (Issue #96)


This is an external email.

Hi, Dear Author,
Thanks for your nice work.
I have recently been testing your open-source algorithm and noticed some drift when working with MCD data. Could you suggest which parameters I could adjust to optimize the results for this dataset？
2024-08-29.11-56-13.png (view on web)<https://github.com/user-attachments/assets/0ffa6529-2441-45c3-9afe-bfdd74c94d66>
2024-08-29.11-56-45.png (view on web)<https://github.com/user-attachments/assets/2d6ce8fb-7ea3-4b32-a91d-62ae020a079d>
image.png (view on web)<https://github.com/user-attachments/assets/522bcfeb-f4ec-4ec5-b738-da14b3c66814>
Thanks.

―

**Comment by Joanna-HE** [comment]
What’s more, use point-lip-grid-map branch to have a more stable performance

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: chengwei ***@***.***>
发送时间: Thursday, August 29, 2024 11:59:13 AM
收件人: hku-mars/Point-LIO ***@***.***>
抄送: Subscribed ***@***.***>
主题: [hku-mars/Point-LIO] Mapping Problem on MCD Dataset (Issue #96)


This is an external email.

Hi, Dear Author,
Thanks for your nice work.
I have recently been testing your open-source algorithm and noticed some drift when working with MCD data. Could you suggest which parameters I could adjust to optimize the results for this dataset？
2024-08-29.11-56-13.png (view on web)<https://github.com/user-attachments/assets/0ffa6529-2441-45c3-9afe-bfdd74c94d66>
2024-08-29.11-56-45.png (view on web)<https://github.com/user-attachments/assets/2d6ce8fb-7ea3-4b32-a91d-62ae020a079d>
image.png (view on web)<https://github.com/user-attachments/assets/522bcfeb-f4ec-4ec5-b738-da14b3c66814>
Thanks.

―

**Comment by chengwei0427** [comment]
Thanks for your kindly reply,the algorithm performed very well.

![2024-08-29 13-41-50屏幕截图](https://github.com/user-attachments/assets/aef35c3a-40ed-49fb-9799-4ae4f9d5e870)
