### ISSUE TITLE
关于状态更新后的协方差矩阵

### ISSUE THREAD

**Issue by LittleDang** [hku-mars/Point-LIO#97]
作者你好，我在观看代码和论文的时候发现代码里面在状态更新后协方差矩阵并没有像论文一样进行最后一步（公式24）的变换。
请问这是为什么呢？

这是代码里的状态更新
![update](https://github.com/user-attachments/assets/5d23f7df-9bbe-4121-8d82-e17c983fef6c)
这是论文里对应的部分
![J](https://github.com/user-attachments/assets/8a0d5f7d-ee56-49e2-8e38-eb8e8b876577)

**Comment by Joanna-HE** [comment]
cov reset是做了一次误差空间重投影。如果residual非常小的话，这一步收益不大。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: LittleDang ***@***.***>
发送时间: Friday, August 30, 2024 2:08:10 PM
收件人: hku-mars/Point-LIO ***@***.***>
抄送: Subscribed ***@***.***>
主题: [hku-mars/Point-LIO] 关于状态更新后的协方差矩阵 (Issue #97)


This is an external email.

作者你好，我在观看代码和论文的时候发现代码里面在状态更新后协方差矩阵并没有像论文一样进行最后一步（公式24）的变换。
请问这是为什么呢？

这是代码里的状态更新
update.png (view on web)<https://github.com/user-attachments/assets/5d23f7df-9bbe-4121-8d82-e17c983fef6c>
这是论文里对应的部分
J.png (view on web)<https://github.com/user-attachments/assets/8a0d5f7d-ee56-49e2-8e38-eb8e8b876577>

―

**Comment by LittleDang** [comment]
懂啦，感谢回复
